services:
  browser-use-webui:
    build:
      context: .
      dockerfile: Dockerfile
    # Coolify will configure the domains and ports based on your UI settings.
    # Add your secrets (API keys, VNC_PASSWORD) in the Coolify Secrets tab.
    environment:
      - BROWSER_DEBUGGING_HOST=0.0.0.0
      - KEEP_BROWPER_OPEN=true
      - DISPLAY=:99
    volumes:
      - browser-data:/app/data/chrome_data
    restart: unless-stopped
    shm_size: '2gb'
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5901"]

volumes:
  browser-data: